[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "wolf"
version = "2.1"
description = "A library using wolf core to implement applications for services automation"
authors = ["sedelpeuch <sebastien@delpeuch.net>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.scripts]
notion_latex = "wolf.template:main"

[tool.poetry.dependencies]
python = "^3.8"
wolf-core = "^2.0.1"
unidecode = "^1.2.0"
pygit2 = "^1.6.1"
pygithub = "^1.59.0"
notion2md = "^2.8.3"

[packages]
wolf = { path = "wolf", develop = false }