name: ✨ Demande d'amélioration
description: Ajout d'une amélioration
labels: "enhancement"
assignees: sedelpeuch
body:
- type: textarea
  attributes:
    label: Objectif
    description: Une description claire de l'objectif de l'amélioration
  validations:
    required: true
- type: textarea
  attributes:
    label: Cas d'utilisation
    description: Une description du cas d'utilisation de l'amélioration
  validations:
    required: true
