name: Deploy

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          git submodule init
          git submodule update
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate
          pip install poetry
          cd core && poetry install
          cd .. && poetry install
      - name: Test with unittest
        run: |
          source venv/bin/activate
          cd tests && python -m unittest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          pip3 install poetry==1.5.0

      - name: Install dependencies and compile wolf package with Poetry
        run: |
          poetry install
          poetry build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/."
          target: "~/wolf/"

      - name: SSH and install package
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            python3 -m venv ~/wolf/venv
            source ~/wolf/venv/bin/activate
            poetry install ~/wolf/wolf_package.whl
            sudo python install.py