name: Publish to Test PyPI

on:
  release:
    types: [ created ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate
          pip install poetry
          poetry install

      - name: Build Python package
        run: python -m build --sdist --wheel .

      - name: Publish to Test PyPi
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repositories: "https://test.pypi.org/legacy/"